FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "NLibrary.Migration/NLibrary.Migration.csproj"
RUN dotnet build "NLibrary.Migration/NLibrary.Migration.csproj" --no-restore -c Release -o /build

WORKDIR /build
ENTRYPOINT ["dotnet", "NLibrary.Migration.dll"]