FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "NLibrary.Api/NLibrary.Api.csproj"
RUN dotnet publish "NLibrary.Api/NLibrary.Api.csproj" --no-restore -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS final
WORKDIR /app
COPY --from=build /publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "NLibrary.Api.dll"]