version: '3'
name: nlibrary
services:
  api:
    container_name: nlibrary-api
    build:
      context: ../src/
      dockerfile: ../docker/dockerfiles/Dockerfile.Api
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=NLibrary;User Id=sa;Password=Administrator1337!;TrustServerCertificate=True
    networks:
      - common
    depends_on:
      migration:
        condition: service_completed_successfully

  migration:
    container_name: nlibrary-migration
    build:
      context: ../src/
      dockerfile: ../docker/dockerfiles/Dockerfile.Migration
    environment:
      - CONNECTION_STRING=Server=mssql;Database=NLibrary;User Id=sa;Password=Administrator1337!;TrustServerCertificate=True
    networks:
      - common
    depends_on:
      mssql:
        condition: service_healthy

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nlibrary-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Administrator1337!
    ports:
      - "1434:1433"
    networks:
      - common
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-U",
          "sa",
          "-P",
          "Administrator1337!",
          "-Q",
          "SELECT 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  common:


volumes:
  mssql-data:
